import React, { useEffect } from "react";
import { FaCheckCircle } from "react-icons/fa";
import { Helmet } from "react-helmet";
import { useLocation } from "react-router-dom";

import solarBg from "../../assets/solar-services.jpg";
import onGrid from "../../assets/on-grid.jpeg";
import offGrid from "../../assets/off-grid.jpeg";
import inverter from "../../assets/inverter-system.jpg";
import battery from "../../assets/solar-batteries.jpg";

import Footer from "../Footer/Footer";

const services = [
  {
    title: "On-Grid Solar",
    id: "ongrid",
    description:
      "On-grid solar systems connect to the utility grid, allowing you to generate electricity and reduce energy bills. Excess power can be fed back into the grid for credit, making it a cost-effective and sustainable solution. Ideal for homes and businesses looking to harness solar energy efficiently.",
    image: onGrid,
    checklist: [
      "Grid Connection",
      "Energy Savings",
      "Net Metering",
      "High Efficiency",
      "Easy Installation",
      "Low Maintenance",
    ],
  },
  {
    title: "Off-Grid Solar",
    id: "offgrid",
    description:
      "Off-grid solar systems operate independently of the utility grid, providing power in remote locations or areas without reliable access to electricity. With battery storage, these systems ensure continuous power supply, offering freedom from utility dependency and reduced energy costs.",
    image: offGrid,
    checklist: [
      "Independent Operation",
      "Battery Storage",
      "Energy Independence",
      "Remote Location Support",
      "Reliable Power Supply",
      "Low Maintenance",
    ],
  },
  {
    title: "Inverter",
    id: "inverter",
    description:
      "Inverters convert the DC (direct current) electricity generated by solar panels into AC (alternating current) power, which is used by most household appliances. They are essential for making solar energy usable and ensuring smooth, efficient operation of your solar system.",
    image: inverter,
    checklist: [
      "DC to AC Conversion",
      "High Efficiency",
      "Compact Design",
      "Long Lifespan",
      "Grid-Compatible",
      "Real-Time Monitoring",
    ],
  },
  {
    title: "Battery",
    id: "battery",
    description:
      "Solar batteries store excess energy generated by solar panels for later use, ensuring a constant power supply even when the sun isn’t shining. They enhance energy independence and efficiency, making them essential for off-grid systems and backup power solutions.",
    image: battery,
    checklist: [
      "Energy Storage",
      "Backup Power",
      "Long Lifespan",
      "Fast Charging",
      "Deep Discharge Capability",
      "Low Maintenance",
    ],
  },
];

const SolarServicesPage = () => {
  const location = useLocation();

  useEffect(() => {
    if (location.hash) {
      const id = location.hash.replace("#", "");
      const section = document.getElementById(id);
      if (section) {
        setTimeout(() => {
          section.scrollIntoView({ behavior: "smooth", block: "center" });
        }, 300);
      }
    }
  }, [location]);

  return (
    <>
      <Helmet>
        <title>Solar Services | On-Grid, Off-Grid, Inverters & Batteries – Techkisan Automation</title>
        <meta
          name="description"
          content="Explore Techkisan's advanced solar services including on-grid and off-grid solar systems, inverters, and solar batteries for homes and businesses. Power your future sustainably."
        />
        <meta
          name="keywords"
          content="solar services, on-grid solar, off-grid solar, solar inverters, solar batteries, renewable energy, solar power system, solar energy solutions"
        />
        <link rel="canonical" href="https://www.techkisan.com/solarservices" />
        <meta property="og:title" content="Solar Services | On-Grid, Off-Grid, Inverters & Batteries – Techkisan Automation" />
        <meta
          property="og:description"
          content="Advanced solar solutions from Techkisan Automation including on-grid and off-grid solar, inverters, and batteries. Harness clean energy for your home or business."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://www.techkisan.com/solarservices" />
        <meta property="og:image" content="https://www.techkisan.com/assets/solar-services.jpg" />
        <script type="application/ld+json">
          {JSON.stringify({
            "@context": "https://schema.org",
            "@type": "WebPage",
            "name": "Solar Services",
            "url": "https://www.techkisan.com/solarservices",
            "description":
              "Explore Techkisan's advanced solar services including on-grid and off-grid solar systems, inverters, and batteries for homes and businesses. Power your future sustainably.",
            "breadcrumb": {
              "@type": "BreadcrumbList",
              "itemListElement": [
                {
                  "@type": "ListItem",
                  "position": 1,
                  "name": "Home",
                  "item": "https://www.techkisan.com"
                },
                {
                  "@type": "ListItem",
                  "position": 2,
                  "name": "Solar Services",
                  "item": "https://www.techkisan.com/solarservices"
                }
              ]
            },
            "publisher": {
              "@type": "Organization",
              "name": "Techkisan Automation",
              "logo": {
                "@type": "ImageObject",
                "url": "https://www.techkisan.com/logo.png"
              }
            }
          })}
        </script>
      </Helmet>

      <div>
        {/* Parallax Section */}
        <section
          className="relative bg-cover bg-center h-96"
          style={{ backgroundImage: `url(${solarBg})` }}
        >
          <div className="absolute inset-0 bg-black bg-opacity-50 flex items-center justify-center">
            <div className="text-center text-white">
              <h1 className="text-4xl font-bold">Solar Services</h1>
              <p className="mt-2">
                "Powering the Future with Clean, Sustainable Energy"
              </p>
            </div>
          </div>
        </section>

        {/* Services Section */}
        <div className="container mx-auto py-16 px-6 max-w-7xl">
          <h2 className="text-3xl font-bold text-center text-gray-800 mb-12">
            Our Solar Solutions
          </h2>

          <div className="grid gap-10 lg:grid-cols-1 relative">
            {services.map((service, index) => (
              <div
                key={index}
                id={service.id}
                className="relative group flex flex-col lg:flex-row bg-white shadow-lg rounded-lg overflow-hidden transform transition-all duration-300 hover:scale-105 hover:z-10"
              >
                {/* Left - Image */}
                <div className="lg:w-1/3">
                  <img
                    src={service.image}
                    alt={service.title}
                    className="w-full max-h-64 object-cover"
                  />
                </div>

                {/* Right - Content */}
                <div className="lg:w-2/3 p-6 flex flex-col justify-center relative z-10">
                  <div className="bg-gray-100 p-4 rounded-lg shadow">
                    <h3 className="text-xl font-semibold text-gray-800">
                      {service.title}
                    </h3>
                    <p className="text-gray-600 mt-2">{service.description}</p>
                  </div>

                  {/* Checklist */}
                  <ul className="mt-4 grid grid-cols-3 gap-4 text-gray-700">
                    {service.checklist.map((item, i) => (
                      <li key={i} className="flex items-center gap-2">
                        <span className="text-green-500">
                          <FaCheckCircle />
                        </span>
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default SolarServicesPage;
